
filetype plugin on
filetype indent on
syntax enable

set autoread
set ruler
set hidden

set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set ignorecase
set smartcase

set hlsearch
set incsearch

set lazyredraw
set showmatch

set noerrorbells
set novisualbell

set encoding=utf8

set ffs=unix,dos,mac

set nobackup
set nowb
set noswapfile

set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

set ai
set si
set nowrap

set laststatus=2

