#!/bin/bash
#~/.bash_profile: excuted by bash(1)
#
#	1. Aliases
#	2. Prompt
#	3. Env
#	4. Func
#

#
#	1. Aliases
#
alias la="ls -A"
alias ll="ls -lhA"
alias ..="cd .."
alias ....="cd ../.."
alias altchrome="open -n -a 'Google Chrome' --args --user-data-dir=${HOME}/.local/cache/chrome"

#
#	2. Prompt
#
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"
PS1="\u@\h ${GREEN}\w${RESET}>"

#
#	3. Env
#
export GOPATH="$HOME/Code/go"
export PATH="$HOME/.local/bin:$GOPATH/bin:$PATH"
export HISTCONTROL=ignoreboth

#
#	4. Functions
#
# go to a folder easily in your gopath
function gogo() {
	local d=$1
	if [[ -z $d ]]; then
		echo "You need to specify a project name."
		return 1
	fi
	if [[ "$d" == github* ]]; then
		d=$(echo "$d" | sed 's/.*\///')
	fi
	d=${d%/}
	local path=( $(find "${GOPATH}/src" \( -type d -o -type l \) -iname "$d"  | awk '{print length, $0;}' | sort -n | awk '{print $2}') )
	if [ "${path[0]}" == "" ] || [ "${path[*]}" == "" ]; then
		echo "Could not find a directory named $d in $GOPATH"
		return 1
	fi
	cd "${path[0]}" || return 1
}

function dmake() {
    is_running="$(docker ps | grep cdocker)"
    if [[ ! $is_running ]] ; then
        docker stop cdocker
        docker rm cdocker
        docker run -d  -t --name cdocker -v "$(pwd)":/src zachneal/cdocker
    fi
    docker exec -t -u "$(id -u)" cdocker make
}

