#!/bin/bash
#~/.bash_profile: excuted by bash(1)
#
#	1. Aliases
#	2. Prompt
#	3. Env
#	4. Func
#	5. Options
#

#
#	1. Aliases
#
alias la="ls -A"
alias ll="ls -lhA"
alias ..="cd .."
alias ....="cd ../.."
alias altchrome="open -n -a 'Google Chrome' --args --user-data-dir=${HOME}/.local/cache/chrome"

#
#	2. Prompt
#
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"
PS1="\u@\h ${GREEN}\w${RESET}>"

#
#	3. Env
#
export GOPATH="$HOME/Code/go"
export PATH="$HOME/.local/bin:$GOPATH/bin:$PATH"
export HISTCONTROL=ignoreboth

#
#	4. Functions
#
# go to a folder easily in your gopath
function gogo() {
	local d=$1
	if [[ -z $d ]]; then
		echo "You need to specify a project name."
		return 1
	fi
	if [[ "$d" == github* ]]; then
		d=$(echo "$d" | sed 's/.*\///')
	fi
	d=${d%/}
	local path=( $(find "${GOPATH}/src" \( -type d -o -type l \) -iname "$d"  | awk '{print length, $0;}' | sort -n | awk '{print $2}') )
	if [ "${path[0]}" == "" ] || [ "${path[*]}" == "" ]; then
		echo "Could not find a directory named $d in $GOPATH"
		return 1
	fi
	cd "${path[0]}" || return 1
}

function lncode() {
	local base="$(basename $PWD)"
	local name="${HOME}/Code/${base}"
	if [ -f "${name}"]; then
		echo "file already exists"
		return 1
	fi
	ln -s "${PWD}" "${name}" || return 1
}

# Create a new directory and enter it
mkd() {
	mkdir -p "$@"
	cd "$@" || exit
}

# Make a temporary directory and enter it
tmpd() {
	local dir
	if [ $# -eq 0 ]; then
		dir=$(mktemp -d)
	else
		dir=$(mktemp -d -t "${1}.XXXXXXXXXX")
	fi
	cd "$dir" || exit
}

#
#	5. Options
#
shopt -s checkwinsize
# fix typos with cd
shopt -s cdspell

export PATH="$HOME/.cargo/bin:$PATH"
